### PR TITLE
basic elemnets for pledge-info component in place.

### PR DESCRIPTION
**Pull request by James9446**

### CODE REVIEW

**Comment by James9446** [comment]
@Chazie9, @ChaseWNorton, @openmichael,
 
Hey, guys please review this pull request. This is just a simple implementation of the pledge-info component. FYI I am calling the main top right div the pledge-info div and the other main div with dynamic components the pledge-support div. 

For this implementation, I created and manually populated the state with an object that will contain all the information that needs to be updated for each product. I also set in place all the classes necessary for styling based on what elements share a visual similarity. Those classes don't have any style rules in place yet. I have created a separate ticket on Trello for every class.

I decided for simplicity to put everything in a <p> tag but I am definitely interested if anyone has any other suggestions or feels there is a better approach. 

Thank you,

**Comment by ChaseWNorton** [comment]
Just an opinion - might want to consider making the pledge info component state full as it seems to have a lot of data/props being passed to it. 

Besides that - it looks great!

**Comment by openmichael** [comment]
I think this is nice for the simple implementation.

**Comment by James9446** [comment]
@Chazie9, @ChaseWNorton, @openmichael,

I believe I have successfully updated my pull request. I refactored my component into a stateful component. Any suggestions or comments are of course welcome.

Thank you,

**Comment by ChaseWNorton** [comment]
looks great dawg. merge approved on my end

**Pull request merged**
